### ISSUE TITLE
I know you're not the creator, buuuut

### ISSUE THREAD

**Issue by bramnet** [pakoito/MarI-O#3]
To make a long story short, and I had this problem on two seperate machines: Whenever I try to load a pool, I get the error "NLua.Exceptions.LuaScriptException: [string "main"]:339: attempt to index field 'neurons' (a nil value)" from the Lua Console output.
Now, I was able to look at line 339, but to be honest, I don't understand Lua enough to try and debug it. Does anyone have a fix?

**Comment by nathanielcwm** [comment]
got the same problem :(

**Comment by nathanielcwm** [comment]
@bramnet got a solution you have to run it with an older version of bizhawk. works perfectly on 1.11.7

**Comment by wts42** [comment]
Changing LUA core worked for me. Menubar -> Config -> Customize -> Advanced -> Lua Core -> Lua+LuaInterface

**Comment by borromeotlhs** [comment]
so if it works on 1.11.7, which version was it not working on?

**Comment by bramnet** [comment]
> so if it works on 1.11.7, which version was it not working on?

As far as I know, the current version (been a while since I've updated though) 2.2.1

**Comment by borromeotlhs** [comment]
If I can resolve whether this code is safe to work with without signing my soul away, I'll try bringing it up absent looking at it.  In your opinion as someone who has already looked at it, is it possible to "just run" this without compiling?  And if so, do you have compilation instructions?

Thanks!

**Comment by bramnet** [comment]
> If I can resolve whether this code is safe to work with without signing my soul away, I'll try bringing it up absent looking at it. In your opinion as someone who has already looked at it, is it possible to "just run" this without compiling? And if so, do you have compilation instructions?

I'm not entirely sure what you're talking about.
In case you haven't read the readme file, this isn't a program you "compile" or "just run", but it's a script (lua) that you load up in a specific emulator while running a copy of either Super Mario Bros. or Super Mario World in said emulator.
If you're interested in running this script yourself, there's a fixed version that currently exists that runs a tad smoother than the original that also doesn't contain this bug when running it on a newer version of the emulator ( https://github.com/mam91/Neat-Genetic-Mario ).

**Comment by borromeotlhs** [comment]
You are correct, as I have stated as much: I didn't read the code.  I am researching the provenance of this stuff so that I ensure using it, downloading it, redistributing it, etc. doesn't infringe anyone's rights.  Especially as I dislike the legal gray area around emulation and the use of someone else's IP as the baseline upon which anything is layered.  Luckily, I own SMW, so the DMCA provides me the ability to make a backup of my own cartridge. 

Thanks for the info.  I'll check that repo out :)  Did you still want this issue resolved, or was this an issue you found before you found the newer repo you're now pointing to?
