### ISSUE TITLE
The SMW "Bot" is not working

### ISSUE THREAD

**Issue by shittygunner** [pakoito/MarI-O#4]
this is the error that appears:

LuaInterface.LuaScriptException: [string "main"]:35: attempt to get length of global 'ButtonNames' (a nil value)

**Comment by borromeotlhs** [comment]
Do you have any more details.  I'm interested in using this for fun, and wouldn't mind fixing up any issues others have had if I see the same issues.  I don't think I will, as I am dope like that, but also like fixing deadended project code for the simple fact that digital archaeologists will wonder: "why did he bother?"

**Comment by borromeotlhs** [comment]
This is because the ButtonNames is probably not resolving.  So the unary length call on the `ButtonNames` variable, if it is nil, will fail.  

I, however, have not run this code, don't know what version of this code, the version of bizhawk, nor the version of the [prereqs](https://github.com/TASVideos/BizHawk-Prereqs/releases) you are using.  Perhaps you could provide more information and I can deduce why before I try to look at compiling this?

**Comment by borromeotlhs** [comment]
Or building or whatever, as Lua is a 'glue language' coded in C for use in C, IIRC. . .
